/*
SELECT * 
 FROM MENU_CAB 
 WHERE IDIOMA = 'SPN'
ORDER BY ORDEN

SELECT * 
  FROM MENU_ITEM
WHERE 1=1
*/  

-- PERSONAL DE PRUEA 'CORTI12' y 'CORTI1'

SELECT * 
 FROM MENU_CAB C
 JOIN MENU_ITEM I ON I.ID_MENU = C.ID_MENU
 WHERE 1=1
   AND C.IDIOMA = 'SPN'
   AND I.IDIOMA = 'SPN'
   AND EXISTS (SELECT 1 
                 FROM ACCESOS A
				 JOIN PERSONAL P ON P.ID_PERSONAL = A.ID_PERSONAL
				WHERE A.ID_MENU_ITEM = I.ID_MENU_ITEM
				  AND P.ID_PERSONAL = 'CORTI12')
ORDER BY C.ORDEN, I.ORDEN

SELECT ID_PERSONAL, USER_ID, USER_PASSWORD
  FROM PERSONAL P
WHERE 1=1
